version: '3.8'

services:
  market-bot:
    image: market-bot:latest
    container_name: market-bot
    restart: always
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN= # Your discord bot token
      - CLIENT_ID= # Your discord bot client id
      - REDIS_URL=redis://:thisIsALocalPasswordDoNotUseInProductionLmao@redis:6379
      - START_CAPITAL=1000.00
      - START_ITEMS_AMOUNT=100
      - PAYOUT_AMOUNT=100.00
      - SESSION_TIME_IN_MINUTES=10
      - MARKET_OPENING_IN_HOURS=7
      - MARKET_CLOSING_IN_HOURS=23

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass thisIsALocalPasswordDoNotUseInProductionLmao
    volumes:
      - db-data:/data
    ports:
      - "6379:6379"

volumes:
    db-data:
      driver: local
